// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBsE9y8RTUWYVqAaoqFMuY7fsjIPr_Cas',
    appId: '1:21519965328:web:e4e7d1856a2f1320a5cc15',
    messagingSenderId: '21519965328',
    projectId: 'raa-podham',
    authDomain: 'raa-podham.firebaseapp.com',
    databaseURL:
        'https://raa-podham-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raa-podham.firebasestorage.app',
    measurementId: 'G-K5XHTJQJJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_KqHrG46Y2fGfmL85UEpXCwc2rNkmeA',
    appId: '1:21519965328:android:290dbda3c7fb4e3ba5cc15',
    messagingSenderId: '21519965328',
    projectId: 'raa-podham',
    databaseURL: 'https://raa-podham-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raa-podham.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANR_G3qcwc9KxEm33ZMj03hjELBxqchws',
    appId: '1:21519965328:ios:f0c72caa4d389375a5cc15',
    messagingSenderId: '21519965328',
    projectId: 'raa-podham',
    databaseURL: 'https://raa-podham-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raa-podham.firebasestorage.app',
    androidClientId: '21519965328-p2u91m785uca54luj8le2fpkr2niv0n4.apps.googleusercontent.com',
    iosClientId: '21519965328-mefmpsitcv4o2bftpr2do1scgingfc2k.apps.googleusercontent.com',
    iosBundleId: 'in.manojreddy.raaPodham',
  );
}
